[package]
name = "ai_prop"
version = "0.1.0"
edition = "2024"

[dependencies]
ai_infra = { git = "https://github.com/soniapi/ai-infra" }
dotenvy = "0.15"
diesel = { version = "2.2.0", features = ["postgres_backend"]}
calamine = "0.31.0"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tonic = "0.12"
prost = "0.13"

[build-dependencies]
protobuf-src = "2.1.1"
tonic-build = "0.12"

[dev-dependencies]
reqwest = { version = "0.13.2", features = ["json"] }
